language: python
python:
  - "3.3"

env:
  - CFLAGS="-O0"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "export PBT_PLUGINS_PATH=$PBT_PLUGINS_PATH:plugins/"

# command to run tests
# Don't change the way that the test are called
script: python3 -m unittest discover -s tests
script: python3 -m unittest discover -s plugins/new
script: python3 -m unittest discover -s plugins/check
script: python3 -m unittest discover -s plugins/install
script: python3 -m unittest discover -s plugins/run
script: python3 -m unittest discover -s plugins/setup

