language: python
python:
  - "3.3"
#Make two builds one for testing and the other as a user setup
env:
  - SYSTEM=false
  - SYSTEM=true

# command to install dependencies
install:
  - 'if [ "$SYSTEM" = false ] ; then pip install -r requirements.txt; fi'
  - 'if [ "$SYSTEM" = false ] ; then export PBT_PLUGINS_PATH=$PBT_PLUGINS_PATH:plugins/; fi'

# command to run tests
# Don't change the way that the test are called
script: 
  # Unit Testing 
  - 'if [ "$SYSTEM" = false ] ; then python3 -m unittest discover -s test/; fi'
  - 'if [ "$SYSTEM" = false ] ; then python3 -m unittest discover -s plugins/new; fi'
  - 'if [ "$SYSTEM" = false ] ; then python3 -m unittest discover -s plugins/check; fi'
  - 'if [ "$SYSTEM" = false ] ; then python3 -m unittest discover -s plugins/install; fi'
  - 'if [ "$SYSTEM" = false ] ; then python3 -m unittest discover -s plugins/run; fi'
  - 'if [ "$SYSTEM" = false ] ; then python3 -m unittest discover -s plugins/setup; fi'
  - 'if [ "$SYSTEM" = false ] ; then python3 -m unittest discover -s plugins/try; fi'
  - 'if [ "$SYSTEM" = false ] ; then python3 -m unittest discover -s plugins/help; fi'
  - 'if [ "$SYSTEM" = false ] ; then python3 -m unittest discover -s plugins/dump; fi'
  - 'if [ "$SYSTEM" = false ] ; then python3 -m unittest discover -s plugins/test; fi'

  # Build testing
  - 'if [ "$SYSTEM" = true ] ; then python3 setup.py install; fi'
  - 'if [ "$SYSTEM" = true ] ; then pbt help; fi'
  - 'if [ "$SYSTEM" = true ] ; then echo "myflaskapp" | pbt new; fi'
  - 'if [ "$SYSTEM" = true ] ; then cd myflaskapp; fi'
  - 'if [ "$SYSTEM" = true ] ; then pbt dump; fi'
  - 'if [ "$SYSTEM" = true ] ; then pbt install; fi'
  - 'if [ "$SYSTEM" = true ] ; then pbt test; fi'
  - 'if [ "$SYSTEM" = true ] ; then pbt check; fi'
  - 'if [ "$SYSTEM" = true ] ; then pbt setup; fi'
